apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Chart.Name }}-manager
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: manager
        image: "{{ .Values.manager.image }}:{{ .Values.manager.tag }}"
        imagePullPolicy: "{{ .Values.manager.pullPolicy }}"
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
{{ if .Values.workload.hpa.enabled }}
        - name: WORKLOAD_HPA_DURATION
          value: '{{ .Values.workload.hpa.duration }}'
        - name: WORKLOAD_HPA_REQUEST_RATE
          value: '{{ .Values.workload.hpa.rate }}'
{{ end }}
{{ if .Values.workload.vpa.enabled }}
        - name: WORKLOAD_VPA_DURATION
          value: '{{ .Values.workload.vpa.duration }}'
        - name: WORKLOAD_VPA_REQUEST_RATE
          value: '{{ .Values.workload.vpa.rate }}'
{{ end }}
