{{ if .Values.workload.hpa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-nginx-hpa
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-nginx-hpa
{{ end }}

{{ if .Values.workload.vpa.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-nginx-vpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-nginx-vpa
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}-nginx-vpa
{{ end }}
